function(use_pack_fun PACKAGE_NAME PAGE_TYPE)
    message("build page = ${PACKAGE_NAME}")
    include(InstallRequiredSystemLibraries)
    if (CMAKE_CURRENT_SOURCE_DIR STREQUAL CMAKE_SOURCE_DIR)
       # set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/License.txt")
        set(CPACK_PACKAGE_VERSION_MAJOR "${${PACKAGE_NAME}_VERSION_MAJOR}")
        set(CPACK_PACKAGE_VERSION_MINOR "${${PACKAGE_NAME}_VERSION_MINOR}")
        set(CPACK_PACKAGE_VERSION_PATCH "${${PACKAGE_NAME}_VERSION_PATCH}")
        set(CPACK_GENERATOR "ZIP")
        set(CPACK_PACKAGE_NAME "${PACKAGE_NAME}")
        set(CPACK_PACKAGE_FILE_NAME "${PACKAGE_NAME}")
        include(CPack)
    endif()
endfunction(use_pack_fun)
